services:
  - type: web
    name: nclex-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false   # Render will use your Supabase DATABASE_URL (set in Dashboard)
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
