services:
  # Database
  - type: pserv
    name: nclex-db
    env: postgresql
    plan: free
    databaseName: nclex_db
    user: nclex_user

  # Web Service  
  - type: web
    name: nclex-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nclex-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"